
const fetchCountryCode = () => {
    return data
}

const data = [
    {
        "Iso2": "AF",
        "Name": "Afghanistan",
        "Iso3": "AFG",
        "Unicode": "afghanistan",
        "Dial": "+93",
        "Currency": "AFN",
        "Capital": "Kabul",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Afghanistan.svg"
    },
    {
        "Iso2": "AL",
        "Name": "Albania",
        "Iso3": "ALB",
        "Unicode": "albania",
        "Dial": "+355",
        "Currency": "ALL",
        "Capital": "Tirana",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg"
    },
    {
        "Iso2": "DZ",
        "Name": "Algeria",
        "Iso3": "DZA",
        "Unicode": "algeria",
        "Dial": "+213",
        "Currency": "DZD",
        "Capital": "Algiers",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg",
        "Number": "213"
    },
    {
        "Iso2": "AD",
        "Name": "Andorra",
        "Iso3": "AND",
        "Unicode": "andorra",
        "Dial": "+376",
        "Currency": "EUR",
        "Capital": "Andorra la Vella",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg",
        "Number": "376"
    },
    {
        "Iso2": "AO",
        "Name": "Angola",
        "Iso3": "AGO",
        "Unicode": "angola",
        "Dial": "+244",
        "Currency": "AOA",
        "Capital": "Luanda",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg",
        "Number": "244"
    },
    {
        "Iso2": "AI",
        "Name": "Anguilla",
        "Iso3": "AIA",
        "Unicode": "anguilla",
        "Dial": "+1-264",
        "Currency": "XCD",
        "Capital": "The Valley",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Anguilla.svg",
        "Number": "1 264"
    },
    {
        "Iso2": "AG",
        "Name": "Antigua and Barbuda",
        "Iso3": "ATG",
        "Unicode": "antigua_barbuda",
        "Dial": "+1-268",
        "Currency": "XCD",
        "Capital": "St. John's",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg",
        "Number": "1268"
    },
    {
        "Iso2": "AR",
        "Name": "Argentina",
        "Iso3": "ARG",
        "Unicode": "argentina",
        "Dial": "+54",
        "Currency": "ARS",
        "Capital": "Buenos Aires",
        "Continent": "SA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        "Number": "54"
    },
    {
        "Iso2": "AM",
        "Name": "Armenia",
        "Iso3": "ARM",
        "Unicode": "armenia",
        "Dial": "+374",
        "Currency": "AMD",
        "Capital": "Yerevan",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg",
        "Number": "374"
    },
    {
        "Iso2": "AW",
        "Name": "Aruba",
        "Iso3": "ABW",
        "Unicode": "aruba",
        "Dial": "+297",
        "Currency": "AWG",
        "Capital": "Oranjestad",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Aruba.svg",
        "Number": "297"
    },
    {
        "Iso2": "AU",
        "Name": "Australia",
        "Iso3": "AUS",
        "Unicode": "australia",
        "Dial": "+61",
        "Currency": "AUD",
        "Capital": "Canberra",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg",
        "Number": "61"
    },
    {
        "Iso2": "AT",
        "Name": "Austria",
        "Iso3": "AUT",
        "Unicode": "austria",
        "Dial": "+43",
        "Currency": "EUR",
        "Capital": "Vienna",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg",
        "Number": "43"
    },
    {
        "Iso2": "AZ",
        "Name": "Azerbaijan",
        "Iso3": "AZE",
        "Unicode": "azerbaijan",
        "Dial": "+994",
        "Currency": "AZN",
        "Capital": "Baku",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg",
        "Number": "994"
    },
    {
        "Iso2": "BS",
        "Name": "Bahamas",
        "Iso3": "BHS",
        "Unicode": "bahamas",
        "Dial": "+1-242",
        "Currency": "BSD",
        "Capital": "Nassau",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg",
        "Number": "1 242"
    },
    {
        "Iso2": "BH",
        "Name": "Bahrain",
        "Iso3": "BHR",
        "Unicode": "bahrain",
        "Dial": "+973",
        "Currency": "BHD",
        "Capital": "Manama",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg",
        "Number": "973"
    },
    {
        "Iso2": "BD",
        "Name": "Bangladesh",
        "Iso3": "BGD",
        "Unicode": "bangladesh",
        "Dial": "+880",
        "Currency": "BDT",
        "Capital": "Dhaka",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg",
        "Number": "880"
    },
    {
        "Iso2": "BB",
        "Name": "Barbados",
        "Iso3": "BRB",
        "Unicode": "barbados",
        "Dial": "+1-246",
        "Currency": "BBD",
        "Capital": "Bridgetown",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg",
        "Number": "1 246"
    },
    {
        "Iso2": "BY",
        "Name": "Belarus",
        "Iso3": "BLR",
        "Unicode": "belarus",
        "Dial": "+375",
        "Currency": "BYR",
        "Capital": "Minsk",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg",
        "Number": "375"
    },
    {
        "Iso2": "BE",
        "Name": "Belgium",
        "Iso3": "BEL",
        "Unicode": "belgium",
        "Dial": "+32",
        "Currency": "EUR",
        "Capital": "Brussels",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg",
        "Number": "32"
    },
    {
        "Iso2": "BZ",
        "Name": "Belize",
        "Iso3": "BLZ",
        "Unicode": "belize",
        "Dial": "+501",
        "Currency": "BZD",
        "Capital": "Belmopan",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg",
        "Number": "501"
    },
    {
        "Iso2": "BJ",
        "Name": "Benin",
        "Iso3": "BEN",
        "Unicode": "benin",
        "Dial": "+229",
        "Currency": "XOF",
        "Capital": "Porto-Novo",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg",
        "Number": "229"
    },
    {
        "Iso2": "BM",
        "Name": "Bermuda",
        "Iso3": "BMU",
        "Unicode": "bermuda",
        "Dial": "+1-441",
        "Currency": "BMD",
        "Capital": "Hamilton",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bermuda.svg",
        "Number": "1 441"
    },
    {
        "Iso2": "BT",
        "Name": "Bhutan",
        "Iso3": "BTN",
        "Unicode": "bhutan",
        "Dial": "+975",
        "Currency": "BTN",
        "Capital": "Thimphu",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg",
        "Number": "975"
    },
    {
        "Iso2": "BA",
        "Name": "Bosnia and Herzegovina",
        "Iso3": "BIH",
        "Unicode": "bosnia_herzegovina",
        "Dial": "387",
        "Currency": "BAM",
        "Capital": "Sarajevo",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg",
        "Number": "387"
    },
    {
        "Iso2": "BW",
        "Name": "Botswana",
        "Iso3": "BWA",
        "Unicode": "botswana",
        "Dial": "+267",
        "Currency": "BWP",
        "Capital": "Gaborone",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg",
        "Number": "267"
    },
    {
        "Iso2": "BV",
        "Name": "Bouvet Island",
        "Iso3": "BVT",
        "Unicode": "🇧🇻",
        "Dial": "+55",
        "Currency": "NOK",
        "Capital": "",
        "Continent": "AN",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg",
        "Number": "55"
    },
    {
        "Iso2": "BR",
        "Name": "Brazil",
        "Iso3": "BRA",
        "Unicode": "brazil",
        "Dial": "+55",
        "Currency": "BRL",
        "Capital": "Brasilia",
        "Continent": "SA",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg",
        "Number": "55"
    },
    {
        "Iso2": "IO",
        "Name": "British Indian Ocean Territory",
        "Iso3": "IOT",
        "Unicode": "british_indian_ocean_territory",
        "Dial": "246",
        "Currency": "USD",
        "Capital": "Diego Garcia",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_the_British_Indian_Ocean_Territory.svg",
        "Number": "246"
    },
    {
        "Iso2": "BG",
        "Name": "Bulgaria",
        "Iso3": "BGR",
        "Unicode": "bulgaria",
        "Dial": "+359",
        "Currency": "BGN",
        "Capital": "Sofia",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg",
        "Number": "359"
    },
    {
        "Iso2": "BF",
        "Name": "Burkina Faso",
        "Iso3": "BFA",
        "Unicode": "burkina_faso",
        "Dial": "+226",
        "Currency": "XOF",
        "Capital": "Ouagadougou",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg",
        "Number": "226"
    },
    {
        "Iso2": "BI",
        "Name": "Burundi",
        "Iso3": "BDI",
        "Unicode": "burundi",
        "Dial": "+257",
        "Currency": "BIF",
        "Capital": "Bujumbura",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg",
        "Number": "257"
    },
    {
        "Iso2": "KH",
        "Name": "Cambodia",
        "Iso3": "KHM",
        "Unicode": "cambodia",
        "Dial": "+855",
        "Currency": "KHR",
        "Capital": "Phnom Penh",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg",
        "Number": "855"
    },
    {
        "Iso2": "CM",
        "Name": "Cameroon",
        "Iso3": "CMR",
        "Unicode": "cameroon",
        "Dial": "+237",
        "Currency": "XAF",
        "Capital": "Yaounde",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg",
        "Number": "237"
    },
    {
        "Iso2": "CA",
        "Name": "Canada",
        "Iso3": "CAN",
        "Unicode": "canada",
        "Dial": "+1",
        "Currency": "CAD",
        "Capital": "Ottawa",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/c/cf/Flag_of_Canada.svg",
        "Number": "1"
    },
    {
        "Iso2": "CV",
        "Name": "Cape Verde",
        "Iso3": "CPV",
        "Unicode": "cape_verde",
        "Dial": "+238",
        "Currency": "CVE",
        "Capital": "Praia",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg",
        "Number": "238"
    },
    {
        "Iso2": "KY",
        "Name": "Cayman Islands",
        "Iso3": "CYM",
        "Unicode": "cayman_islands",
        "Dial": "+1-345",
        "Currency": "KYD",
        "Capital": "George Town",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_the_Cayman_Islands.svg",
        "Number": "1345"
    },
    {
        "Iso2": "CF",
        "Name": "Central African Republic",
        "Iso3": "CAF",
        "Unicode": "central_african_republic",
        "Dial": "+236",
        "Currency": "XAF",
        "Capital": "Bangui",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg",
        "Number": "236"
    },
    {
        "Iso2": "TD",
        "Name": "Chad",
        "Iso3": "TCD",
        "Unicode": "chad",
        "Dial": "+235",
        "Currency": "XAF",
        "Capital": "N'Djamena",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg",
        "Number": "235"
    },
    {
        "Iso2": "CL",
        "Name": "Chile",
        "Iso3": "CHL",
        "Unicode": "chile",
        "Dial": "+56",
        "Currency": "CLP",
        "Capital": "Santiago",
        "Continent": "SA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg",
        "Number": "56"
    },
    {
        "Iso2": "CN",
        "Name": "China",
        "Iso3": "CHN",
        "Unicode": "cn",
        "Dial": "+86",
        "Currency": "CNY",
        "Capital": "Beijing",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg",
        "Number": "86"
    },
    {
        "Iso2": "CX",
        "Name": "Christmas Island",
        "Iso3": "CXR",
        "Unicode": "christmas_island",
        "Dial": "+61",
        "Currency": "AUD",
        "Capital": "Flying Fish Cove",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/67/Flag_of_Christmas_Island.svg",
        "Number": "61"
    },
    {
        "Iso2": "CO",
        "Name": "Colombia",
        "Iso3": "COL",
        "Unicode": "colombia",
        "Dial": "+57",
        "Currency": "COP",
        "Capital": "Bogota",
        "Continent": "SA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg",
        "Number": "57"
    },
    {
        "Iso2": "KM",
        "Name": "Comoros",
        "Iso3": "COM",
        "Unicode": "comoros",
        "Dial": "+269",
        "Currency": "KMF",
        "Capital": "Moroni",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg",
        "Number": "269"
    },
    {
        "Iso2": "CK",
        "Name": "Cook Islands",
        "Iso3": "COK",
        "Unicode": "cook_islands",
        "Dial": "+682",
        "Currency": "NZD",
        "Capital": "Avarua",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_the_Cook_Islands.svg",
        "Number": "682"
    },
    {
        "Iso2": "CR",
        "Name": "Costa Rica",
        "Iso3": "CRI",
        "Unicode": "costa_rica",
        "Dial": "+506",
        "Currency": "CRC",
        "Capital": "San Jose",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Costa_Rica_%28state%29.svg",
        "Number": "506"
    },
    {
        "Iso2": "HR",
        "Name": "Croatia",
        "Iso3": "HRV",
        "Unicode": "croatia",
        "Dial": "+385",
        "Currency": "HRK",
        "Capital": "Zagreb",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg",
        "Number": "385"
    },
    {
        "Iso2": "CU",
        "Name": "Cuba",
        "Iso3": "CUB",
        "Unicode": "cuba",
        "Dial": "+53",
        "Currency": "CUP",
        "Capital": "Havana",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg",
        "Number": "53"
    },
    {
        "Iso2": "CY",
        "Name": "Cyprus",
        "Iso3": "CYP",
        "Unicode": "cyprus",
        "Dial": "+357",
        "Currency": "EUR",
        "Capital": "Nicosia",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg",
        "Number": "357"
    },
    {
        "Iso2": "CZ",
        "Name": "Czech Republic",
        "Iso3": "CZE",
        "Unicode": "czech_republic",
        "Dial": "+420",
        "Currency": "CZK",
        "Capital": "Prague",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg",
        "Number": "420"
    },
    {
        "Iso2": "DK",
        "Name": "Denmark",
        "Iso3": "DNK",
        "Unicode": "denmark",
        "Dial": "+45",
        "Currency": "DKK",
        "Capital": "Copenhagen",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg",
        "Number": "45"
    },
    {
        "Iso2": "DJ",
        "Name": "Djibouti",
        "Iso3": "DJI",
        "Unicode": "djibouti",
        "Dial": "+253",
        "Currency": "DJF",
        "Capital": "Djibouti",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg",
        "Number": "253"
    },
    {
        "Iso2": "DM",
        "Name": "Dominica",
        "Iso3": "DMA",
        "Unicode": "dominica",
        "Dial": "+1-767",
        "Currency": "XCD",
        "Capital": "Roseau",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg",
        "Number": "1 767"
    },
    {
        "Iso2": "DO",
        "Name": "Dominican Republic",
        "Iso3": "DOM",
        "Unicode": "dominican_republic",
        "Dial": "+1-809 and 1-829",
        "Currency": "DOP",
        "Capital": "Santo Domingo",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg",
        "Number": "1 849"
    },
    {
        "Iso2": "EC",
        "Name": "Ecuador",
        "Iso3": "ECU",
        "Unicode": "ecuador",
        "Dial": "+593",
        "Currency": "USD",
        "Capital": "Quito",
        "Continent": "SA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg",
        "Number": "593"
    },
    {
        "Iso2": "EG",
        "Name": "Egypt",
        "Iso3": "EGY",
        "Unicode": "egypt",
        "Dial": "+20",
        "Currency": "EGP",
        "Capital": "Cairo",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg",
        "Number": "20"
    },
    {
        "Iso2": "SV",
        "Name": "El Salvador",
        "Iso3": "SLV",
        "Unicode": "el_salvador",
        "Dial": "+503",
        "Currency": "USD",
        "Capital": "San Salvador",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg",
        "Number": "503"
    },
    {
        "Iso2": "GQ",
        "Name": "Equatorial Guinea",
        "Iso3": "GNQ",
        "Unicode": "equatorial_guinea",
        "Dial": "+240",
        "Currency": "XAF",
        "Capital": "Malabo",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg",
        "Number": "240"
    },
    {
        "Iso2": "ER",
        "Name": "Eritrea",
        "Iso3": "ERI",
        "Unicode": "eritrea",
        "Dial": "+291",
        "Currency": "ERN",
        "Capital": "Asmara",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg",
        "Number": "291"
    },
    {
        "Iso2": "EE",
        "Name": "Estonia",
        "Iso3": "EST",
        "Unicode": "estonia",
        "Dial": "+372",
        "Currency": "EUR",
        "Capital": "Tallinn",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg",
        "Number": "372"
    },
    {
        "Iso2": "ET",
        "Name": "Ethiopia",
        "Iso3": "ETH",
        "Unicode": "ethiopia",
        "Dial": "+251",
        "Currency": "ETB",
        "Capital": "Addis Ababa",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg",
        "Number": "251"
    },
    {
        "Iso2": "FO",
        "Name": "Faroe Islands",
        "Iso3": "FRO",
        "Unicode": "faroe_islands",
        "Dial": "+298",
        "Currency": "DKK",
        "Capital": "Torshavn",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Flag_of_the_Faroe_Islands.svg",
        "Number": "298"
    },
    {
        "Iso2": "FJ",
        "Name": "Fiji",
        "Iso3": "FJI",
        "Unicode": "fiji",
        "Dial": "+679",
        "Currency": "FJD",
        "Capital": "Suva",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg",
        "Number": "679"
    },
    {
        "Iso2": "FI",
        "Name": "Finland",
        "Iso3": "FIN",
        "Unicode": "finland",
        "Dial": "+358",
        "Currency": "EUR",
        "Capital": "Helsinki",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg",
        "Number": "358"
    },
    {
        "Iso2": "FR",
        "Name": "France",
        "Iso3": "FRA",
        "Unicode": "fr",
        "Dial": "+33",
        "Currency": "EUR",
        "Capital": "Paris",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg",
        "Number": "33"
    },
    {
        "Iso2": "GF",
        "Name": "French Guiana",
        "Iso3": "GUF",
        "Unicode": "french_guiana",
        "Dial": "+594",
        "Currency": "EUR",
        "Capital": "Cayenne",
        "Continent": "SA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_French_Guiana.svg",
        "Number": "594"
    },
    {
        "Iso2": "PF",
        "Name": "French Polynesia",
        "Iso3": "PYF",
        "Unicode": "french_polynesia",
        "Dial": "+689",
        "Currency": "XPF",
        "Capital": "Papeete",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/db/Flag_of_French_Polynesia.svg",
        "Number": "689"
    },
    {
        "Iso2": "GA",
        "Name": "Gabon",
        "Iso3": "GAB",
        "Unicode": "gabon",
        "Dial": "+241",
        "Currency": "XAF",
        "Capital": "Libreville",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg",
        "Number": "241"
    },
    {
        "Iso2": "GM",
        "Name": "Gambia",
        "Iso3": "GMB",
        "Unicode": "gambia",
        "Dial": "+220",
        "Currency": "GMD",
        "Capital": "Banjul",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg",
        "Number": "220"
    },
    {
        "Iso2": "GE",
        "Name": "Georgia",
        "Iso3": "GEO",
        "Unicode": "georgia",
        "Dial": "+995",
        "Currency": "GEL",
        "Capital": "Tbilisi",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg",
        "Number": "995"
    },
    {
        "Iso2": "DE",
        "Name": "Germany",
        "Iso3": "DEU",
        "Unicode": "de",
        "Dial": "+49",
        "Currency": "EUR",
        "Capital": "Berlin",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg",
        "Number": "49"
    },
    {
        "Iso2": "GH",
        "Name": "Ghana",
        "Iso3": "GHA",
        "Unicode": "ghana",
        "Dial": "+233",
        "Currency": "GHS",
        "Capital": "Accra",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg",
        "Number": "233"
    },
    {
        "Iso2": "GI",
        "Name": "Gibraltar",
        "Iso3": "GIB",
        "Unicode": "gibraltar",
        "Dial": "+350",
        "Currency": "GIP",
        "Capital": "Gibraltar",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/02/Flag_of_Gibraltar.svg",
        "Number": "350"
    },
    {
        "Iso2": "GR",
        "Name": "Greece",
        "Iso3": "GRC",
        "Unicode": "greece",
        "Dial": "+30",
        "Currency": "EUR",
        "Capital": "Athens",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg",
        "Number": "30"
    },
    {
        "Iso2": "GL",
        "Name": "Greenland",
        "Iso3": "GRL",
        "Unicode": "greenland",
        "Dial": "+299",
        "Currency": "DKK",
        "Capital": "Nuuk",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_Greenland.svg",
        "Number": "299"
    },
    {
        "Iso2": "GD",
        "Name": "Grenada",
        "Iso3": "GRD",
        "Unicode": "grenada",
        "Dial": "+1-473",
        "Currency": "XCD",
        "Capital": "St. George's",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg",
        "Number": "1 473"
    },
    {
        "Iso2": "GP",
        "Name": "Guadeloupe",
        "Iso3": "GLP",
        "Unicode": "guadeloupe",
        "Dial": "+590",
        "Currency": "EUR",
        "Capital": "Basse-Terre",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Guadeloupe_%28local%29.svg",
        "Number": "590"
    },
    {
        "Iso2": "GU",
        "Name": "Guam",
        "Iso3": "GUM",
        "Unicode": "guam",
        "Dial": "+1-671",
        "Currency": "USD",
        "Capital": "Hagatna",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/07/Flag_of_Guam.svg",
        "Number": "1 671"
    },
    {
        "Iso2": "GT",
        "Name": "Guatemala",
        "Iso3": "GTM",
        "Unicode": "guatemala",
        "Dial": "+502",
        "Currency": "GTQ",
        "Capital": "Guatemala City",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg",
        "Number": "502"
    },
    {
        "Iso2": "GG",
        "Name": "Guernsey",
        "Iso3": "GGY",
        "Unicode": "guernsey",
        "Dial": "+44-1481",
        "Currency": "GBP",
        "Capital": "St Peter Port",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Guernsey.svg",
        "Number": "44"
    },
    {
        "Iso2": "GN",
        "Name": "Guinea",
        "Iso3": "GIN",
        "Unicode": "guinea",
        "Dial": "+224",
        "Currency": "GNF",
        "Capital": "Conakry",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg",
        "Number": "224"
    },
    {
        "Iso2": "GW",
        "Name": "Guinea-Bissau",
        "Iso3": "GNB",
        "Unicode": "guinea_bissau",
        "Dial": "+245",
        "Currency": "XOF",
        "Capital": "Bissau",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg",
        "Number": "245"
    },
    {
        "Iso2": "GY",
        "Name": "Guyana",
        "Iso3": "GUY",
        "Unicode": "guyana",
        "Dial": "+592",
        "Currency": "GYD",
        "Capital": "Georgetown",
        "Continent": "SA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg",
        "Number": "592"
    },
    {
        "Iso2": "HT",
        "Name": "Haiti",
        "Iso3": "HTI",
        "Unicode": "haiti",
        "Dial": "+509",
        "Currency": "HTG",
        "Capital": "Port-au-Prince",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg",
        "Number": "509"
    },
    {
        "Iso2": "HM",
        "Name": "Heard Island and McDonald Islands",
        "Iso3": "HMD",
        "Unicode": "🇭🇲",
        "Dial": "+ ",
        "Currency": "AUD",
        "Capital": "",
        "Continent": "AN",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Antarctica.svg",
        "Number": "672"
    },
    {
        "Iso2": "HN",
        "Name": "Honduras",
        "Iso3": "HND",
        "Unicode": "honduras",
        "Dial": "+504",
        "Currency": "HNL",
        "Capital": "Tegucigalpa",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg",
        "Number": "504"
    },
    {
        "Iso2": "HK",
        "Name": "Hong Kong",
        "Iso3": "HKG",
        "Unicode": "hong_kong",
        "Dial": "+852",
        "Currency": "HKD",
        "Capital": "Hong Kong",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Hong_Kong.svg",
        "Number": "852"
    },
    {
        "Iso2": "HU",
        "Name": "Hungary",
        "Iso3": "HUN",
        "Unicode": "hungary",
        "Dial": "+36",
        "Currency": "HUF",
        "Capital": "Budapest",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg",
        "Number": "36"
    },
    {
        "Iso2": "IS",
        "Name": "Iceland",
        "Iso3": "ISL",
        "Unicode": "iceland",
        "Dial": "+354",
        "Currency": "ISK",
        "Capital": "Reykjavik",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg",
        "Number": "354"
    },
    {
        "Iso2": "IN",
        "Name": "India",
        "Iso3": "IND",
        "Unicode": "india",
        "Dial": "+91",
        "Currency": "INR",
        "Capital": "New Delhi",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg",
        "Number": "91"
    },
    {
        "Iso2": "ID",
        "Name": "Indonesia",
        "Iso3": "IDN",
        "Unicode": "indonesia",
        "Dial": "+62",
        "Currency": "IDR",
        "Capital": "Jakarta",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg",
        "Number": "62"
    },
    {
        "Iso2": "IR",
        "Name": "Iran",
        "Iso3": "IRN",
        "Unicode": "iran",
        "Dial": "+98",
        "Currency": "IRR",
        "Capital": "Tehran",
        "Continent": "AS",
        "Flag": " https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg",
        "Number": "98"
    },
    {
        "Iso2": "IQ",
        "Name": "Iraq",
        "Iso3": "IRQ",
        "Unicode": "iraq",
        "Dial": "+964",
        "Currency": "IQD",
        "Capital": "Baghdad",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg",
        "Number": "964"
    },
    {
        "Iso2": "IE",
        "Name": "Ireland",
        "Iso3": "IRL",
        "Unicode": "ireland",
        "Dial": "+353",
        "Currency": "EUR",
        "Capital": "Dublin",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg",
        "Number": "353"
    },
    {
        "Iso2": "IM",
        "Name": "Isle of Man",
        "Iso3": "IMN",
        "Unicode": "isle_of_man",
        "Dial": "+44-1624",
        "Currency": "GBP",
        "Capital": "Douglas, Isle of Man",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_the_Isle_of_Man.svg",
        "Number": "44"
    },
    {
        "Iso2": "IL",
        "Name": "Israel",
        "Iso3": "ISR",
        "Unicode": "israel",
        "Dial": "+972",
        "Currency": "ILS",
        "Capital": "Jerusalem",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg",
        "Number": "972"
    },
    {
        "Iso2": "IT",
        "Name": "Italy",
        "Iso3": "ITA",
        "Unicode": "it",
        "Dial": "+39",
        "Currency": "EUR",
        "Capital": "Rome",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg",
        "Number": "39"
    },
    {
        "Iso2": "JM",
        "Name": "Jamaica",
        "Iso3": "JAM",
        "Unicode": "jamaica",
        "Dial": "+1-876",
        "Currency": "JMD",
        "Capital": "Kingston",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg",
        "Number": "1 876"
    },
    {
        "Iso2": "JP",
        "Name": "Japan",
        "Iso3": "JPN",
        "Unicode": "jp",
        "Dial": "+81",
        "Currency": "JPY",
        "Capital": "Tokyo",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg",
        "Number": "81"
    },
    {
        "Iso2": "JE",
        "Name": "Jersey",
        "Iso3": "JEY",
        "Unicode": "jersey",
        "Dial": "+44-1534",
        "Currency": "GBP",
        "Capital": "Saint Helier",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/1c/Flag_of_Jersey.svg",
        "Number": "44"
    },
    {
        "Iso2": "JO",
        "Name": "Jordan",
        "Iso3": "JOR",
        "Unicode": "jordan",
        "Dial": "+962",
        "Currency": "JOD",
        "Capital": "Amman",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg",
        "Number": "962"
    },
    {
        "Iso2": "KZ",
        "Name": "Kazakhstan",
        "Iso3": "KAZ",
        "Unicode": "kazakhstan",
        "Dial": "+7",
        "Currency": "KZT",
        "Capital": "Astana",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg",
        "Number": "7"
    },
    {
        "Iso2": "KE",
        "Name": "Kenya",
        "Iso3": "KEN",
        "Unicode": "kenya",
        "Dial": "+254",
        "Currency": "KES",
        "Capital": "Nairobi",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg",
        "Number": "254"
    },
    {
        "Iso2": "KI",
        "Name": "Kiribati",
        "Iso3": "KIR",
        "Unicode": "kiribati",
        "Dial": "+686",
        "Currency": "AUD",
        "Capital": "Tarawa",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg",
        "Number": "686"
    },
    {
        "Iso2": "KW",
        "Name": "Kuwait",
        "Iso3": "KWT",
        "Unicode": "kuwait",
        "Dial": "+965",
        "Currency": "KWD",
        "Capital": "Kuwait City",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg",
        "Number": "965"
    },
    {
        "Iso2": "KG",
        "Name": "Kyrgyzstan",
        "Iso3": "KGZ",
        "Unicode": "kyrgyzstan",
        "Dial": "+996",
        "Currency": "KGS",
        "Capital": "Bishkek",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg",
        "Number": "996"
    },
    {
        "Iso2": "LV",
        "Name": "Latvia",
        "Iso3": "LVA",
        "Unicode": "latvia",
        "Dial": "+371",
        "Currency": "EUR",
        "Capital": "Riga",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg",
        "Number": "371"
    },
    {
        "Iso2": "LB",
        "Name": "Lebanon",
        "Iso3": "LBN",
        "Unicode": "lebanon",
        "Dial": "+961",
        "Currency": "LBP",
        "Capital": "Beirut",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg",
        "Number": "961"
    },
    {
        "Iso2": "LS",
        "Name": "Lesotho",
        "Iso3": "LSO",
        "Unicode": "lesotho",
        "Dial": "+266",
        "Currency": "LSL",
        "Capital": "Maseru",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg",
        "Number": "266"
    },
    {
        "Iso2": "LR",
        "Name": "Liberia",
        "Iso3": "LBR",
        "Unicode": "liberia",
        "Dial": "+231",
        "Currency": "LRD",
        "Capital": "Monrovia",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg",
        "Number": "231"
    },
    {
        "Iso2": "LI",
        "Name": "Liechtenstein",
        "Iso3": "LIE",
        "Unicode": "liechtenstein",
        "Dial": "+423",
        "Currency": "CHF",
        "Capital": "Vaduz",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg",
        "Number": "423"
    },
    {
        "Iso2": "LT",
        "Name": "Lithuania",
        "Iso3": "LTU",
        "Unicode": "lithuania",
        "Dial": "+370",
        "Currency": "LTL",
        "Capital": "Vilnius",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg",
        "Number": "370"
    },
    {
        "Iso2": "LU",
        "Name": "Luxembourg",
        "Iso3": "LUX",
        "Unicode": "luxembourg",
        "Dial": "+352",
        "Currency": "EUR",
        "Capital": "Luxembourg",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg",
        "Number": "352"
    },
    {
        "Iso2": "MO",
        "Name": "Macao",
        "Iso3": "MAC",
        "Unicode": "macau",
        "Dial": "+853",
        "Currency": "MOP",
        "Capital": "Macao",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/63/Flag_of_Macau.svg",
        "Number": "853"
    },
    {
        "Iso2": "MG",
        "Name": "Madagascar",
        "Iso3": "MDG",
        "Unicode": "madagascar",
        "Dial": "+261",
        "Currency": "MGA",
        "Capital": "Antananarivo",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg",
        "Number": "261"
    },
    {
        "Iso2": "MW",
        "Name": "Malawi",
        "Iso3": "MWI",
        "Unicode": "malawi",
        "Dial": "+265",
        "Currency": "MWK",
        "Capital": "Lilongwe",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg",
        "Number": "265"
    },
    {
        "Iso2": "MY",
        "Name": "Malaysia",
        "Iso3": "MYS",
        "Unicode": "malaysia",
        "Dial": "+60",
        "Currency": "MYR",
        "Capital": "Kuala Lumpur",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg",
        "Number": "60"
    },
    {
        "Iso2": "MV",
        "Name": "Maldives",
        "Iso3": "MDV",
        "Unicode": "maldives",
        "Dial": "+960",
        "Currency": "MVR",
        "Capital": "Male",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg",
        "Number": "960"
    },
    {
        "Iso2": "ML",
        "Name": "Mali",
        "Iso3": "MLI",
        "Unicode": "mali",
        "Dial": "+223",
        "Currency": "XOF",
        "Capital": "Bamako",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg",
        "Number": "223"
    },
    {
        "Iso2": "MT",
        "Name": "Malta",
        "Iso3": "MLT",
        "Unicode": "malta",
        "Dial": "+356",
        "Currency": "EUR",
        "Capital": "Valletta",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg",
        "Number": "356"
    },
    {
        "Iso2": "MH",
        "Name": "Marshall Islands",
        "Iso3": "MHL",
        "Unicode": "marshall_islands",
        "Dial": "+692",
        "Currency": "USD",
        "Capital": "Majuro",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg",
        "Number": "692"
    },
    {
        "Iso2": "MQ",
        "Name": "Martinique",
        "Iso3": "MTQ",
        "Unicode": "martinique",
        "Dial": "+596",
        "Currency": "EUR",
        "Capital": "Fort-de-France",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/5/52/Flag_of_Martinique.svg",
        "Number": "596"
    },
    {
        "Iso2": "MR",
        "Name": "Mauritania",
        "Iso3": "MRT",
        "Unicode": "mauritania",
        "Dial": "+222",
        "Currency": "MRO",
        "Capital": "Nouakchott",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg",
        "Number": "222"
    },
    {
        "Iso2": "MU",
        "Name": "Mauritius",
        "Iso3": "MUS",
        "Unicode": "mauritius",
        "Dial": "+230",
        "Currency": "MUR",
        "Capital": "Port Louis",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg",
        "Number": "230"
    },
    {
        "Iso2": "YT",
        "Name": "Mayotte",
        "Iso3": "MYT",
        "Unicode": "mayotte",
        "Dial": "+262",
        "Currency": "EUR",
        "Capital": "Mamoudzou",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg",
        "Number": "262"
    },
    {
        "Iso2": "MX",
        "Name": "Mexico",
        "Iso3": "MEX",
        "Unicode": "mexico",
        "Dial": "+52",
        "Currency": "MXN",
        "Capital": "Mexico City",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg",
        "Number": "52"
    },
    {
        "Iso2": "MC",
        "Name": "Monaco",
        "Iso3": "MCO",
        "Unicode": "monaco",
        "Dial": "+377",
        "Currency": "EUR",
        "Capital": "Monaco",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg",
        "Number": "377"
    },
    {
        "Iso2": "MN",
        "Name": "Mongolia",
        "Iso3": "MNG",
        "Unicode": "mongolia",
        "Dial": "+976",
        "Currency": "MNT",
        "Capital": "Ulan Bator",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg",
        "Number": "976"
    },
    {
        "Iso2": "ME",
        "Name": "Montenegro",
        "Iso3": "MNE",
        "Unicode": "montenegro",
        "Dial": "+382",
        "Currency": "EUR",
        "Capital": "Podgorica",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg",
        "Number": "382"
    },
    {
        "Iso2": "MS",
        "Name": "Montserrat",
        "Iso3": "MSR",
        "Unicode": "montserrat",
        "Dial": "+1-664",
        "Currency": "XCD",
        "Capital": "Plymouth",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Montserrat.svg",
        "Number": "1664"
    },
    {
        "Iso2": "MA",
        "Name": "Morocco",
        "Iso3": "MAR",
        "Unicode": "morocco",
        "Dial": "+212",
        "Currency": "MAD",
        "Capital": "Rabat",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg",
        "Number": "212"
    },
    {
        "Iso2": "MZ",
        "Name": "Mozambique",
        "Iso3": "MOZ",
        "Unicode": "mozambique",
        "Dial": "+258",
        "Currency": "MZN",
        "Capital": "Maputo",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg",
        "Number": "258"
    },
    {
        "Iso2": "MM",
        "Name": "Myanmar",
        "Iso3": "MMR",
        "Unicode": "myanmar",
        "Dial": "+95",
        "Currency": "MMK",
        "Capital": "Nay Pyi Taw",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg",
        "Number": "95"
    },
    {
        "Iso2": "NA",
        "Name": "Namibia",
        "Iso3": "NAM",
        "Unicode": "namibia",
        "Dial": "+264",
        "Currency": "NAD",
        "Capital": "Windhoek",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg",
        "Number": "264"
    },
    {
        "Iso2": "NR",
        "Name": "Nauru",
        "Iso3": "NRU",
        "Unicode": "nauru",
        "Dial": "+674",
        "Currency": "AUD",
        "Capital": "Yaren",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Nauru.svg",
        "Number": "674"
    },
    {
        "Iso2": "NP",
        "Name": "Nepal",
        "Iso3": "NPL",
        "Unicode": "nepal",
        "Dial": "+977",
        "Currency": "NPR",
        "Capital": "Kathmandu",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg",
        "Number": "977"
    },
    {
        "Iso2": "NL",
        "Name": "Netherlands",
        "Iso3": "NLD",
        "Unicode": "netherlands",
        "Dial": "+31",
        "Currency": "EUR",
        "Capital": "Amsterdam",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg",
        "Number": "31"
    },
    {
        "Iso2": "NC",
        "Name": "New Caledonia",
        "Iso3": "NCL",
        "Unicode": "new_caledonia",
        "Dial": "+687",
        "Currency": "XPF",
        "Capital": "Noumea",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/23/Flag_of_New_Caledonia.svg",
        "Number": "687"
    },
    {
        "Iso2": "NZ",
        "Name": "New Zealand",
        "Iso3": "NZL",
        "Unicode": "new_zealand",
        "Dial": "+64",
        "Currency": "NZD",
        "Capital": "Wellington",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg",
        "Number": "64"
    },
    {
        "Iso2": "NI",
        "Name": "Nicaragua",
        "Iso3": "NIC",
        "Unicode": "nicaragua",
        "Dial": "+505",
        "Currency": "NIO",
        "Capital": "Managua",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg",
        "Number": "505"
    },
    {
        "Iso2": "NE",
        "Name": "Niger",
        "Iso3": "NER",
        "Unicode": "niger",
        "Dial": "+227",
        "Currency": "XOF",
        "Capital": "Niamey",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg",
        "Number": "227"
    },
    {
        "Iso2": "NG",
        "Name": "Nigeria",
        "Iso3": "NGA",
        "Unicode": "nigeria",
        "Dial": "+234",
        "Currency": "NGN",
        "Capital": "Abuja",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg",
        "Number": "234"
    },
    {
        "Iso2": "NU",
        "Name": "Niue",
        "Iso3": "NIU",
        "Unicode": "niue",
        "Dial": "+683",
        "Currency": "NZD",
        "Capital": "Alofi",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Niue.svg",
        "Number": "683"
    },
    {
        "Iso2": "NF",
        "Name": "Norfolk Island",
        "Iso3": "NFK",
        "Unicode": "norfolk_island",
        "Dial": "+672",
        "Currency": "AUD",
        "Capital": "Kingston",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Norfolk_Island.svg",
        "Number": "672"
    },
    {
        "Iso2": "MP",
        "Name": "Northern Mariana Islands",
        "Iso3": "MNP",
        "Unicode": "northern_mariana_islands",
        "Dial": "+1-670",
        "Currency": "USD",
        "Capital": "Saipan",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Flag_of_the_Northern_Mariana_Islands.svg",
        "Number": "1 670"
    },
    {
        "Iso2": "NO",
        "Name": "Norway",
        "Iso3": "NOR",
        "Unicode": "norway",
        "Dial": "+47",
        "Currency": "NOK",
        "Capital": "Oslo",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg",
        "Number": "47"
    },
    {
        "Iso2": "OM",
        "Name": "Oman",
        "Iso3": "OMN",
        "Unicode": "oman",
        "Dial": "+968",
        "Currency": "OMR",
        "Capital": "Muscat",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg",
        "Number": "968"
    },
    {
        "Iso2": "PK",
        "Name": "Pakistan",
        "Iso3": "PAK",
        "Unicode": "pakistan",
        "Dial": "+92",
        "Currency": "PKR",
        "Capital": "Islamabad",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg",
        "Number": "92"
    },
    {
        "Iso2": "PW",
        "Name": "Palau",
        "Iso3": "PLW",
        "Unicode": "palau",
        "Dial": "+680",
        "Currency": "USD",
        "Capital": "Melekeok",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg",
        "Number": "680"
    },
    {
        "Iso2": "PA",
        "Name": "Panama",
        "Iso3": "PAN",
        "Unicode": "panama",
        "Dial": "+507",
        "Currency": "PAB",
        "Capital": "Panama City",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg",
        "Number": "507"
    },
    {
        "Iso2": "PG",
        "Name": "Papua New Guinea",
        "Iso3": "PNG",
        "Unicode": "papua_new_guinea",
        "Dial": "+675",
        "Currency": "PGK",
        "Capital": "Port Moresby",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg",
        "Number": "675"
    },
    {
        "Iso2": "PY",
        "Name": "Paraguay",
        "Iso3": "PRY",
        "Unicode": "paraguay",
        "Dial": "+595",
        "Currency": "PYG",
        "Capital": "Asuncion",
        "Continent": "SA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg",
        "Number": "595"
    },
    {
        "Iso2": "PE",
        "Name": "Peru",
        "Iso3": "PER",
        "Unicode": "peru",
        "Dial": "+51",
        "Currency": "PEN",
        "Capital": "Lima",
        "Continent": "SA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg",
        "Number": "51"
    },
    {
        "Iso2": "PH",
        "Name": "Philippines",
        "Iso3": "PHL",
        "Unicode": "philippines",
        "Dial": "+63",
        "Currency": "PHP",
        "Capital": "Manila",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg",
        "Number": "63"
    },
    {
        "Iso2": "PN",
        "Name": "Pitcairn",
        "Iso3": "PCN",
        "Unicode": "pitcairn_islands",
        "Dial": "+870",
        "Currency": "NZD",
        "Capital": "Adamstown",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_the_Pitcairn_Islands.svg",
        "Number": "870"
    },
    {
        "Iso2": "PL",
        "Name": "Poland",
        "Iso3": "POL",
        "Unicode": "poland",
        "Dial": "+48",
        "Currency": "PLN",
        "Capital": "Warsaw",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg",
        "Number": "48"
    },
    {
        "Iso2": "PT",
        "Name": "Portugal",
        "Iso3": "PRT",
        "Unicode": "portugal",
        "Dial": "+351",
        "Currency": "EUR",
        "Capital": "Lisbon",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg",
        "Number": "351"
    },
    {
        "Iso2": "PR",
        "Name": "Puerto Rico",
        "Iso3": "PRI",
        "Unicode": "puerto_rico",
        "Dial": "+1-787 and 1-939",
        "Currency": "USD",
        "Capital": "San Juan",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Puerto_Rico.svg",
        "Number": "1 939"
    },
    {
        "Iso2": "QA",
        "Name": "Qatar",
        "Iso3": "QAT",
        "Unicode": "qatar",
        "Dial": "+974",
        "Currency": "QAR",
        "Capital": "Doha",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg",
        "Number": "974"
    },
    {
        "Iso2": "RO",
        "Name": "Romania",
        "Iso3": "ROU",
        "Unicode": "romania",
        "Dial": "+40",
        "Currency": "RON",
        "Capital": "Bucharest",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg",
        "Number": "40"
    },
    {
        "Iso2": "RW",
        "Name": "Rwanda",
        "Iso3": "RWA",
        "Unicode": "rwanda",
        "Dial": "+250",
        "Currency": "RWF",
        "Capital": "Kigali",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg",
        "Number": "250"
    },
    {
        "Iso2": "KN",
        "Name": "Saint Kitts and Nevis",
        "Iso3": "KNA",
        "Unicode": "st_kitts_nevis",
        "Dial": "+1-869",
        "Currency": "XCD",
        "Capital": "Basseterre",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg",
        "Number": "1 869"
    },
    {
        "Iso2": "LC",
        "Name": "Saint Lucia",
        "Iso3": "LCA",
        "Unicode": "st_lucia",
        "Dial": "+1-758",
        "Currency": "XCD",
        "Capital": "Castries",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg",
        "Number": "1 758"
    },
    {
        "Iso2": "PM",
        "Name": "Saint Pierre and Miquelon",
        "Iso3": "SPM",
        "Unicode": "st_pierre_miquelon",
        "Dial": "+508",
        "Currency": "EUR",
        "Capital": "Saint-Pierre",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_Saint-Pierre_and_Miquelon.svg",
        "Number": "508"
    },
    {
        "Iso2": "VC",
        "Name": "Saint Vincent and the Grenadines",
        "Iso3": "VCT",
        "Unicode": "st_vincent_grenadines",
        "Dial": "+1-784",
        "Currency": "XCD",
        "Capital": "Kingstown",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg",
        "Number": "1 784"
    },
    {
        "Iso2": "WS",
        "Name": "Samoa",
        "Iso3": "WSM",
        "Unicode": "samoa",
        "Dial": "+685",
        "Currency": "WST",
        "Capital": "Apia",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg",
        "Number": "685"
    },
    {
        "Iso2": "SM",
        "Name": "San Marino",
        "Iso3": "SMR",
        "Unicode": "san_marino",
        "Dial": "+378",
        "Currency": "EUR",
        "Capital": "San Marino",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg",
        "Number": "378"
    },
    {
        "Iso2": "ST",
        "Name": "Sao Tome and Principe",
        "Iso3": "STP",
        "Unicode": "sao_tome_principe",
        "Dial": "+239",
        "Currency": "STD",
        "Capital": "Sao Tome",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Sao_Tome_and_Principe.svg",
        "Number": "239"
    },
    {
        "Iso2": "SA",
        "Name": "Saudi Arabia",
        "Iso3": "SAU",
        "Unicode": "saudi_arabia",
        "Dial": "+966",
        "Currency": "SAR",
        "Capital": "Riyadh",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg",
        "Number": "966"
    },
    {
        "Iso2": "SN",
        "Name": "Senegal",
        "Iso3": "SEN",
        "Unicode": "senegal",
        "Dial": "+221",
        "Currency": "XOF",
        "Capital": "Dakar",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg",
        "Number": "221"
    },
    {
        "Iso2": "RS",
        "Name": "Serbia",
        "Iso3": "SRB",
        "Unicode": "serbia",
        "Dial": "+381",
        "Currency": "RSD",
        "Capital": "Belgrade",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg",
        "Number": "381"
    },
    {
        "Iso2": "SC",
        "Name": "Seychelles",
        "Iso3": "SYC",
        "Unicode": "seychelles",
        "Dial": "+248",
        "Currency": "SCR",
        "Capital": "Victoria",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg",
        "Number": "248"
    },
    {
        "Iso2": "SL",
        "Name": "Sierra Leone",
        "Iso3": "SLE",
        "Unicode": "sierra_leone",
        "Dial": "+232",
        "Currency": "SLL",
        "Capital": "Freetown",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg",
        "Number": "232"
    },
    {
        "Iso2": "SG",
        "Name": "Singapore",
        "Iso3": "SGP",
        "Unicode": "singapore",
        "Dial": "+65",
        "Currency": "SGD",
        "Capital": "Singapur",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg",
        "Number": "65"
    },
    {
        "Iso2": "SK",
        "Name": "Slovakia",
        "Iso3": "SVK",
        "Unicode": "slovakia",
        "Dial": "+421",
        "Currency": "EUR",
        "Capital": "Bratislava",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg",
        "Number": "421"
    },
    {
        "Iso2": "SI",
        "Name": "Slovenia",
        "Iso3": "SVN",
        "Unicode": "slovenia",
        "Dial": "+386",
        "Currency": "EUR",
        "Capital": "Ljubljana",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg",
        "Number": "386"
    },
    {
        "Iso2": "SB",
        "Name": "Solomon Islands",
        "Iso3": "SLB",
        "Unicode": "solomon_islands",
        "Dial": "+677",
        "Currency": "SBD",
        "Capital": "Honiara",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg",
        "Number": "677"
    },
    {
        "Iso2": "SO",
        "Name": "Somalia",
        "Iso3": "SOM",
        "Unicode": "somalia",
        "Dial": "+252",
        "Currency": "SOS",
        "Capital": "Mogadishu",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg",
        "Number": "252"
    },
    {
        "Iso2": "ZA",
        "Name": "South Africa",
        "Iso3": "ZAF",
        "Unicode": "south_africa",
        "Dial": "+27",
        "Currency": "ZAR",
        "Capital": "Pretoria",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg",
        "Number": "27"
    },
    {
        "Iso2": "GS",
        "Name": "South Georgia and the South Sandwich Islands",
        "Iso3": "SGS",
        "Unicode": "south_georgia_south_sandwich_islands",
        "Dial": "+",
        "Currency": "GBP",
        "Capital": "Grytviken",
        "Continent": "AN",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg",
        "Number": "500"
    },
    {
        "Iso2": "ES",
        "Name": "Spain",
        "Iso3": "ESP",
        "Unicode": "es",
        "Dial": "+34",
        "Currency": "EUR",
        "Capital": "Madrid",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg",
        "Number": "34"
    },
    {
        "Iso2": "LK",
        "Name": "Sri Lanka",
        "Iso3": "LKA",
        "Unicode": "sri_lanka",
        "Dial": "+94",
        "Currency": "LKR",
        "Capital": "Colombo",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg",
        "Number": "94"
    },
    {
        "Iso2": "SD",
        "Name": "Sudan",
        "Iso3": "SDN",
        "Unicode": "sudan",
        "Dial": "+249",
        "Currency": "SDG",
        "Capital": "Khartoum",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg",
        "Number": "249"
    },
    {
        "Iso2": "SZ",
        "Name": "Swaziland",
        "Iso3": "SWZ",
        "Unicode": "swaziland",
        "Dial": "+268",
        "Currency": "SZL",
        "Capital": "Mbabane",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Flag_of_Swaziland.svg",
        "Number": "268"
    },
    {
        "Iso2": "SE",
        "Name": "Sweden",
        "Iso3": "SWE",
        "Unicode": "sweden",
        "Dial": "+46",
        "Currency": "SEK",
        "Capital": "Stockholm",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg",
        "Number": "46"
    },
    {
        "Iso2": "CH",
        "Name": "Switzerland",
        "Iso3": "CHE",
        "Unicode": "switzerland",
        "Dial": "+41",
        "Currency": "CHF",
        "Capital": "Berne",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Switzerland_%28Pantone%29.svg",
        "Number": "41"
    },
    {
        "Iso2": "TW",
        "Name": "Taiwan",
        "Iso3": "TWN",
        "Unicode": "taiwan",
        "Dial": "+886",
        "Currency": "TWD",
        "Capital": "Taipei",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg",
        "Number": "886"
    },
    {
        "Iso2": "TJ",
        "Name": "Tajikistan",
        "Iso3": "TJK",
        "Unicode": "tajikistan",
        "Dial": "+992",
        "Currency": "TJS",
        "Capital": "Dushanbe",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg",
        "Number": "992"
    },
    {
        "Iso2": "TH",
        "Name": "Thailand",
        "Iso3": "THA",
        "Unicode": "thailand",
        "Dial": "+66",
        "Currency": "THB",
        "Capital": "Bangkok",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg",
        "Number": "66"
    },
    {
        "Iso2": "TG",
        "Name": "Togo",
        "Iso3": "TGO",
        "Unicode": "togo",
        "Dial": "+228",
        "Currency": "XOF",
        "Capital": "Lome",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg",
        "Number": "228"
    },
    {
        "Iso2": "TK",
        "Name": "Tokelau",
        "Iso3": "TKL",
        "Unicode": "tokelau",
        "Dial": "+690",
        "Currency": "NZD",
        "Capital": "",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Flag_of_Tokelau.svg",
        "Number": "690"
    },
    {
        "Iso2": "TO",
        "Name": "Tonga",
        "Iso3": "TON",
        "Unicode": "tonga",
        "Dial": "+676",
        "Currency": "TOP",
        "Capital": "Nuku'alofa",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg",
        "Number": "676"
    },
    {
        "Iso2": "TT",
        "Name": "Trinidad and Tobago",
        "Iso3": "TTO",
        "Unicode": "trinidad_tobago",
        "Dial": "+1-868",
        "Currency": "TTD",
        "Capital": "Port of Spain",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg",
        "Number": "1 868"
    },
    {
        "Iso2": "TN",
        "Name": "Tunisia",
        "Iso3": "TUN",
        "Unicode": "tunisia",
        "Dial": "+216",
        "Currency": "TND",
        "Capital": "Tunis",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg",
        "Number": "216"
    },
    {
        "Iso2": "TR",
        "Name": "Turkey",
        "Iso3": "TUR",
        "Unicode": "tr",
        "Dial": "+90",
        "Currency": "TRY",
        "Capital": "Ankara",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
        "Number": "90"
    },
    {
        "Iso2": "TM",
        "Name": "Turkmenistan",
        "Iso3": "TKM",
        "Unicode": "turkmenistan",
        "Dial": "+993",
        "Currency": "TMT",
        "Capital": "Ashgabat",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg",
        "Number": "993"
    },
    {
        "Iso2": "TC",
        "Name": "Turks and Caicos Islands",
        "Iso3": "TCA",
        "Unicode": "turks_caicos_islands",
        "Dial": "+1-649",
        "Currency": "USD",
        "Capital": "Cockburn Town",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg",
        "Number": "1 649"
    },
    {
        "Iso2": "TV",
        "Name": "Tuvalu",
        "Iso3": "TUV",
        "Unicode": "tuvalu",
        "Dial": "+688",
        "Currency": "AUD",
        "Capital": "Funafuti",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg",
        "Number": "688"
    },
    {
        "Iso2": "UG",
        "Name": "Uganda",
        "Iso3": "UGA",
        "Unicode": "uganda",
        "Dial": "+256",
        "Currency": "UGX",
        "Capital": "Kampala",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg",
        "Number": "256"
    },
    {
        "Iso2": "UA",
        "Name": "Ukraine",
        "Iso3": "UKR",
        "Unicode": "ukraine",
        "Dial": "+380",
        "Currency": "UAH",
        "Capital": "Kiev",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg",
        "Number": "380"
    },
    {
        "Iso2": "AE",
        "Name": "United Arab Emirates",
        "Iso3": "ARE",
        "Unicode": "united_arab_emirates",
        "Dial": "+971",
        "Currency": "AED",
        "Capital": "Abu Dhabi",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg",
        "Number": "971"
    },
    {
        "Iso2": "GB",
        "Name": "United Kingdom",
        "Iso3": "GBR",
        "Unicode": "gb",
        "Dial": "+44",
        "Currency": "GBP",
        "Capital": "London",
        "Continent": "EU",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg",
        "Number": "44"
    },
    {
        "Iso2": "US",
        "Name": "United States",
        "Iso3": "USA",
        "Unicode": "us",
        "Dial": "+1",
        "Currency": "USD",
        "Capital": "Washington",
        "Continent": "NA",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
        "Number": "1"
    },
    {
        "Iso2": "UM",
        "Name": "United States Minor Outlying Islands",
        "Iso3": "UMI",
        "Unicode": "🇺🇲",
        "Dial": "+1",
        "Currency": "USD",
        "Capital": "",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
        "Number": "1581"
    },
    {
        "Iso2": "UY",
        "Name": "Uruguay",
        "Iso3": "URY",
        "Unicode": "uruguay",
        "Dial": "+598",
        "Currency": "UYU",
        "Capital": "Montevideo",
        "Continent": "SA",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg",
        "Number": "598"
    },
    {
        "Iso2": "UZ",
        "Name": "Uzbekistan",
        "Iso3": "UZB",
        "Unicode": "uzbekistan",
        "Dial": "+998",
        "Currency": "UZS",
        "Capital": "Tashkent",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg",
        "Number": "998"
    },
    {
        "Iso2": "VU",
        "Name": "Vanuatu",
        "Iso3": "VUT",
        "Unicode": "vanuatu",
        "Dial": "+678",
        "Currency": "VUV",
        "Capital": "Port Vila",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Vanuatu.svg",
        "Number": "678"
    },
    {
        "Iso2": "WF",
        "Name": "Wallis and Futuna",
        "Iso3": "WLF",
        "Unicode": "wallis_futuna",
        "Dial": "+681",
        "Currency": "XPF",
        "Capital": "Mata Utu",
        "Continent": "OC",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/d/d2/Flag_of_Wallis_and_Futuna.svg",
        "Number": "681"
    },
    {
        "Iso2": "YE",
        "Name": "Yemen",
        "Iso3": "YEM",
        "Unicode": "yemen",
        "Dial": "+967",
        "Currency": "YER",
        "Capital": "Sanaa",
        "Continent": "AS",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg",
        "Number": "967"
    },
    {
        "Iso2": "ZM",
        "Name": "Zambia",
        "Iso3": "ZMB",
        "Unicode": "zambia",
        "Dial": "+260",
        "Currency": "ZMK",
        "Capital": "Lusaka",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg",
        "Number": "260"
    },
    {
        "Iso2": "ZW",
        "Name": "Zimbabwe",
        "Iso3": "ZWE",
        "Unicode": "zimbabwe",
        "Dial": "+263",
        "Currency": "ZWL",
        "Capital": "Harare",
        "Continent": "AF",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg",
        "Number": "263"
    }
]

export default {
    fetchCountryCode
};
